# # Nginx ConfigMap
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nginx-config
#   namespace: default
# data:
#   default.conf: |
#     server {
#         listen 3000;
#         server_name localhost;

#         location / {
#             root /usr/share/nginx/html;
#             try_files $uri $uri/ /index.html;
#         }

#         location /static {
#             alias /usr/share/nginx/html/static;
#         }
#     }
# ---
# React App Deployment with Nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: nginx
        image:  harsh9945/my_care_labs:latest # Replace with your Docker image
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
---
# React App Service
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: default
spec:
  selector:
    app: react-app
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: harsh9945/jouls_backend_docke:latest
        ports:
        - containerPort: 5000
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
# Ingress Configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-apps-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: test.jouls.co.in
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: react-app-service
            port:
              number: 3000
      - path: /backend(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 5000
